services:
  
  cms-postgresql:
    image: postgres:15.3
    container_name: cms-postgresql
    ports:
      - "5432:5432" # PostgreSQL default port
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "cms"
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persistent volume for PostgreSQL data
    networks:
      - cms-platform-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cms"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

 
 
  cms-apim:
    build:
      context: ./wso2-stack/apim
      dockerfile: Dockerfile
    container_name: cms-apim
    hostname: localhost
    depends_on:
      cms-postgresql:
        condition: service_healthy
    ports:
      - "8280:8280"      # API Gateway (HTTP)
      - "8243:8243"      # API Gateway (HTTPS)
      - "9443:9443"      # Admin/Publisher Console (HTTPS)
      - "9611:9611"      # Analytics
    volumes:
      - wso2am-data:/home/wso2carbon/wso2am-4.1.0/repository/data
      - wso2am-logs:/home/wso2carbon/wso2am-4.1.0/repository/logs
    networks:
      - cms-platform-net
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:9443/api/am/admin/v0.17/system-info", "-k"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  taly-api:
    build:
      context: ./talyapi
      dockerfile: Dockerfile
    container_name: cms-talyapi
    hostname: localhost
    depends_on:
      cms-postgresql:
        condition: service_healthy
    ports:
      - "9012:9012"   # HTTP
      - "9013:9013"   # HTTPS
    environment:
       - ASPNETCORE_URLS=http://+:9012;https://+:9013
       - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
       - ASPNETCORE_Kestrel__Certificates__Default__Password=Classa9@123
    networks:
      - cms-platform-net
    volumes:
        - ./cert.pfx:/https/cert.pfx
          -
    
    

  cms-jpos:
    build:
      context: ./jpos
      dockerfile: Dockerfile
    container_name: cms-jpos
   
    ports:
      - "5000:5000"   # ISO8583 port
    volumes:
      - ./jpos/deploy:/opt/jpos/deploy
      - ./jpos/config:/opt/jpos/config
    networks:
      - cms-platform-net

  cms-jposee:
    build:
      context: ./jposee
      dockerfile: Dockerfile
    container_name: cms-jposee
    depends_on:
      cms-postgresql:
        condition: service_healthy
    
    ports:
      - "5001:5000"   # ISO 8583 standard
      - "5002:5001"   # ISO 8583 secondary
    volumes:
      - ./jposee/deploy:/opt/jposee/dist/deploy
      - ./jposee/config:/opt/jposee/dist/config
      - ./jposee/log:/opt/jposee/dist/log
      
    networks:
      - cms-platform-net
    environment:
      - JPOS_LOG_LEVEL=info

volumes:
 
  postgres-data:
    driver: local
 
  wso2am-data:
    driver: local
  wso2am-logs:
    driver: local
  talyapihttp:
    driver: local
networks:
  cms-platform-net:
    driver: bridge