FROM wso2/wso2am:4.0.0

# Copy custom configuration files if needed
# COPY api-manager.xml $WSO2_SERVER_HOME/repository/conf/api-manager.xml

# Expose ports
EXPOSE 8280 8243 9443 9611

CMD ["/home/wso2carbon/wso2am-4.0.0/bin/api-manager.sh"]
